model:
  _global:
    feature_dim: 2048
    neck: bnneck
  local:
    hrnet:
      lock: true
      pretrained:
        enabled: true
        path: HRNet/model-11-joints-line-10.pth
      num_joints: 11
  aligned: true

    

dataset: 'Market1501'


random_seed: 42

width: 192
height: 256 

train:
  num_classes: 751
  batch:
    p: 8
    k: 8
  start_epoch: 0
  max_epochs: 200
  loss:
    metric:
      enabled: true
      loss_func: triplet-hard-aligned-reid # triplet, triplet-hard, triplet-hard-aligned-reid
      weight: 1.0
      margin: 0.3
    id:
      enabled: true
      loss_func: cross-entropy-label-smooth # cross-entropy-label-smooth, cross-entropy
      weight: 1.0
      epsilon: 0.1 # available when using cross-entropy-label-smooth
    center:
      enabled: true
      weight: 0.001

  pin_memory: false
  num_workers: 8

  eval_on_n_epochs: 10
  save_on_n_epochs: 20

  
  warmup:
    enabled: true
    iters: 10
    init_lr: 0.0000035
  lr_scheduler:  # MultiStepLR
    init_lr: 0.00035
    milestones: [40, 70, 100,130,150,170]
    gamma: 0.5
  
  
test:
  pin_memory: false
  num_workers: 8
  batch_size: 64
  distance: global # global,local,global_local
  ranks: [1,3,5,10,20]
  reranking: true
use_gpu: true

use_cudnn: true

name: all-losses

output_root_dir: outputs


tensorboard:
  enabled: true